import {
  tomato,
  red,
  crimson,
  pink,
  plum,
  purple,
  violet,
  indigo,
  blue,
  cyan,
  teal,
  green,
  grass,
  orange,
  brown,
  sky,
  mint,
  lime,
  yellow,
  amber,
  mauve,
  tomatoDark,
  redDark,
  crimsonDark,
  pinkDark,
  plumDark,
  purpleDark,
  violetDark,
  indigoDark,
  blueDark,
  cyanDark,
  tealDark,
  greenDark,
  grassDark,
  orangeDark,
  brownDark,
  skyDark,
  mintDark,
  limeDark,
  yellowDark,
  amberDark,
  mauveDark,
} from '@radix-ui/colors'

const gray = {
  gray1: mauve.mauve1,
  gray2: mauve.mauve2,
  gray3: mauve.mauve3,
  gray4: mauve.mauve4,
  gray5: mauve.mauve5,
  gray6: mauve.mauve6,
  gray7: mauve.mauve7,
  gray8: mauve.mauve8,
  gray9: mauve.mauve9,
  gray10: mauve.mauve10,
  gray11: mauve.mauve11,
  gray12: mauve.mauve12,
}

const baseTheme = {
  ...tomato,
  ...red,
  ...crimson,
  ...pink,
  ...plum,
  ...purple,
  ...violet,
  ...indigo,
  ...blue,
  ...cyan,
  ...teal,
  ...green,
  ...grass,
  ...orange,
  ...brown,
  ...sky,
  ...mint,
  ...lime,
  ...yellow,
  ...amber,
  ...gray,
  primary1: indigo.indigo1,
  primary2: indigo.indigo2,
  primary3: indigo.indigo3,
  primary4: indigo.indigo4,
  primary5: indigo.indigo5,
  primary6: indigo.indigo6,
  primary7: indigo.indigo7,
  primary8: indigo.indigo8,
  primary9: indigo.indigo9,
  primary10: indigo.indigo10,
  primary11: indigo.indigo11,
  primary12: indigo.indigo12,

  white: '#ffffff',
  black: '#000000',

  appBackground: '$gray1',
  textTitle: '$gray12',
  shape: '$white',
}

const baseLightTheme = {
  ...baseTheme,
}

const grayDark = {
  gray1: mauveDark.mauve1,
  gray2: mauveDark.mauve2,
  gray3: mauveDark.mauve3,
  gray4: mauveDark.mauve4,
  gray5: mauveDark.mauve5,
  gray6: mauveDark.mauve6,
  gray7: mauveDark.mauve7,
  gray8: mauveDark.mauve8,
  gray9: mauveDark.mauve9,
  gray10: mauveDark.mauve10,
  gray11: mauveDark.mauve11,
  gray12: mauveDark.mauve12,
}

const baseDarkTheme = {
  ...tomatoDark,
  ...redDark,
  ...crimsonDark,
  ...pinkDark,
  ...plumDark,
  ...purpleDark,
  ...violetDark,
  ...indigoDark,
  ...blueDark,
  ...cyanDark,
  ...tealDark,
  ...greenDark,
  ...grassDark,
  ...orangeDark,
  ...brownDark,
  ...skyDark,
  ...mintDark,
  ...limeDark,
  ...yellowDark,
  ...amberDark,
  ...grayDark,
  primary1: '',
  primary2: '',
  primary3: '',
  primary4: '',
  primary5: '',
  primary6: '',
  primary7: '',
  primary8: '',
  primary9: '',
  primary10: '',
  primary11: '',
  primary12: '',

  white: '#ffffff',
  black: '#000000',

  appBackground: '$gray1',
  textTitle: '$gray12',
  shape: '$gray3',
}

export { baseTheme, baseLightTheme, baseDarkTheme }
